# default values for all jobs
language: python

python:
  - "3.6"

dist: bionic

os: linux

#before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh
script: cd tests && sudo ./run_all_tests.sh

install:
    - sudo apt-get install python3-pip tshark
    - sudo pip3 install setuptools cryptography
    - sudo python3 setup.py install
