# default values for all jobs
language: python

python:
  - "3.6"

dist: bionic

os: linux

#before_install: ./.ci/${TRAVIS_OS_NAME}-setup.sh
script: sudo ./tests/legacy/test.sh && ./tests/new_api/test.sh

install:
    - sudo apt-get install python3-pip
    - sudo pip3 install cryptography
    - sudo apt-get install tshark
